### ISSUE TITLE
Pre-trained Weights for Mode='All'

### ISSUE THREAD

**Issue by edessa** [epic-kitchens/VISOR-HOS#10]
Hi,

I am trying to retrieve noun predictions for objects in contact, which seems to be predicted by the network where mode='all' under demo.py. Could you please release the pre-trained weights for that network? This would be very useful to people (like me) working in action understanding. Thank you!

**Comment by ddshan** [comment]
Hi @edessa ,

Sorry, we do not have a model that predicts the nouns of the objects in contact. The mode in the script indicates different types of visualization and "all" means that it visualizes all predicted hands and in-contact object candidates without association while otherwise, it visualizes hands and corresponding in-contact objects after associating.

If you need the noun of the objects, we do have the noun label objects in our annotations. It will be worth looking at our dataset and annotations to see if you can use them.

Let me know if you have other questions!
